### ISSUE TITLE
Allow multiple packages to be passed to program

### ISSUE THREAD

**Issue by nmiyake** [gordonklaus/ineffassign#11]
It would be helpful if multiple packages could be provided to `ineffassign` for analysis. Most other static Go analysis tools support this behavior as well, so would be great to make this consistent. Happy to open a PR if you think this would be reasonable.

**Comment by gordonklaus** [comment]
Makes sense to me.  Go for it.

I don't know what other tools are using, but I guess this is useful https://godoc.org/golang.org/x/tools/go/buildutil#ExpandPatterns

**Comment by dnephin** [comment]
https://github.com/gordonklaus/ineffassign/pull/20
