### ISSUE TITLE
vendor directory

### ISSUE THREAD

**Issue by steenzout** [gordonklaus/ineffassign#12]
if I run

```
$ ineffassign .
```

it will also analyze packages in the `vendor` directory.

if you agree to ignore this I can make a PR.

**Comment by gordonklaus** [comment]
Go for it.

**Comment by steenzout** [comment]
@gordonklaus please review #13 and let me know if you want any further modifications.

cheers!

**Comment by mholt** [comment]
Just wanted to say THANK YOU for this! It's the _only_ test in all of Caddy's CI checks that successfully ignored the `vendor/` folder without crazy hacks. 🙌

**Comment by steenzout** [comment]
@mholt check [h12w/gosweep](https://github.com/h12w/gosweep) ;).
