### ISSUE TITLE
Uncaught ineffective assignment

### ISSUE THREAD

**Issue by benma** [gordonklaus/ineffassign#15]
```Go
package main

import "fmt"

func main() {
	var i int
	i = 3
	i = 5
	fmt.Println(i)
}
```

`$ ineffassign main.go` does not produce any results. It should catch that the `i = 3` assignment was ineffective (its value was never used).

I created the issue because I discovered an unchecked error in my code because of this pattern, i.e.:

```Go
err := someCall()
err = anotherCall()
if err != nil { ... }
```

**Comment by gordonklaus** [comment]
Thanks for pointing this out!  I'll work up a fix.

**Comment by benma** [comment]
Excellent, thank you!
