### ISSUE TITLE
false positive found

### ISSUE THREAD

**Issue by ericlagergren** [gordonklaus/ineffassign#18]
Line https://github.com/ericlagergren/decimal/blob/522450d1e655d86ef13b0bfad42d090a0240ce03/decimal.go#L430 is marked as an ineffectual assign.

**Comment by gordonklaus** [comment]
The assignment to `zm` is indeed ineffectual, as `zm` is not thereafter used.  The right hand side of an assignment happens before the assignment itself.

**Comment by ericlagergren** [comment]
fair enough, I actually fixed this not too long after I created the issue. (`z.unscaled` should be `zm`.)
