### ISSUE TITLE
Uncaught 

### ISSUE THREAD

**Issue by mattdee123** [gordonklaus/ineffassign#24]
```
package foo

func foo() {
    x := 1
    x = 2
    return &x
}
```

The initial assignment is ineffective, but isn't caught here, due to the fact that `x` escapes.

**Comment by CathalC2011** [comment]
The initial assignment is not ineffective, as x will be undefined without it.

**Comment by gordonklaus** [comment]
I'm going to say fixing this is beyond the scope of this tool.  A variable that escapes could end up being used at any point in the program (even after to the apparent ineffective assignment above, if there was synchronization with another goroutine where the use occurred), which only a complete pointer analysis could determine.
