### ISSUE TITLE
Allow to disable check in specific line

### ISSUE THREAD

**Issue by mrostecki** [gordonklaus/ineffassign#27]
It would be nice to allow to ignore checks by writing comment like:

```
// ineffassign: ignore
```

i.e.

```
res := someFunction() // ineffassign: ignore
```

**Comment by gordonklaus** [comment]
The Go language already has a feature for ignoring the result of an assignment, and that is to assign to underscore (`_`).  Or simply omit the left hand side.  If for some reason (documentation?) you want to keep the variable (`res` in your example), just assign it to underscore on the next line (`_ = res`).

Your example doesn't even pass the _compiler's_ checking, and is thus outside the scope of this tool.  As for ignoring _ineffessign_ checks, you'll have to provide compelling reasons (and actual examples) why you don't just fix them instead.

**Comment by mrostecki** [comment]
OK, the concrete example is here:

https://github.com/cilium/cilium/blob/master/pkg/bpf/bpffs.go#L261

Yes, ineffassingn complains about that line:

```
/home/mrostecki/go/src/github.com/cilium/cilium/pkg/bpf/bpffs.go:261:4: ineffectual assignment to err
```

I would like to ignore that error, because it doesn't make sense to me. This assignment should be effectual and `err` variable is returned at the end of function.
