### ISSUE TITLE
Minor: Support go standard use of ./...

### ISSUE THREAD

**Issue by davewichers** [gordonklaus/ineffassign#40]
Most go tools support the use of ./... to mean scan from the current directory down as far as you can go. However, ineffassign responds with this:  "app/dir/...: no such file or directory"

So instead I had to use ./* which seems to work fine by the way.  However, for consistency with other go tools can you add support for ./... too?

**Comment by guerinoni** [comment]
@gordonklaus I think this is closed...

**Comment by gordonklaus** [comment]
fixed by #51
