### ISSUE TITLE
Build failed due to go tool version mismatch

### ISSUE THREAD

**Issue by harishagrawal** [gordonklaus/ineffassign#42]
Appreciate your help with this: (how do I skip this version mismatch)

go test -v 

# unicode/utf8
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# internal/race
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# math/bits
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# runtime/internal/sys
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# unicode
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# runtime/internal/atomic
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# internal/cpu
compile: version "go1.13.5" does not match go tool version "go1.13.6"
# sync/atomic
compile: version "go1.13.5" does not match go tool version "go1.13.6"
FAIL	github.com/gordonklaus/ineffassign [build failed]

**Comment by gordonklaus** [comment]
This is not related to ineffassign.  You may need to reinstall Go.
