### ISSUE TITLE
False positive in the-eye-team/reddit-dl

### ISSUE THREAD

**Issue by nektro** [gordonklaus/ineffassign#45]
I noticed the usage here <https://goreportcard.com/report/github.com/The-Eye-Team/reddit-dl#ineffassign>. In it, I have code very similar to the following..

```go
l := true

if complicatedCondition() {
	l = false
}
if anotherComplicatedCondition() {
	l = false
}
if l {
	// do some code that handles the default case
}
```

and ineffassign is labeling the `l = false` lines as ineffectual assigns. I believe this to be a bug. Conversation welcome :)

**Comment by gordonklaus** [comment]
I took a look and found something similar to the following as well:
```go
if condition() {
    l = false
} else {
    l = false
}
```
which amounts to an unconditional assignment to `l`, making all the preceding assignments ineffectual.  I suppose the bug is that one of these two assignments shouldn't exist?

**Comment by nektro** [comment]
Good point, sorry for the bug.
