### ISSUE TITLE
False positive: string concatenation

### ISSUE THREAD

**Issue by ocket8888** [gordonklaus/ineffassign#60]
Because `ineffassign` doesn't consider types in its checks, it makes the mistake of assuming that the `+` operator is associative. This is not the case for all types - most notably strings.

Here's an example of a small program that does an assignment that is *not* ineffectual, but *does* get flagged as such by `ineffassign`:

```go
package main

import (
	"fmt"
)

const prefix = `prefix `

func main() {
	prefixMe := `a string to prefix`
	// the below line is flagged
	prefixMe = prefix + prefixMe
	fmt.Println(prefixMe)
}
```

([playground](https://play.golang.org/p/2v1vz-s6tBx))

**Comment by gordonklaus** [comment]
The line you indicate is not flagged for me.  Can you check again that the code you posted is as intended?

**Comment by ocket8888** [comment]
hmm... that's actually a MCVE of an issue I was seeing in a much larger file. I'm actually having trouble reproducing it, but the code that does exhibit the problem is here: https://github.com/ocket8888/trafficcontrol/blob/to/restructure-roles/traffic_ops/traffic_ops_golang/user/user.go#L158-L163

I don't understand how it's different from my example. Certainly doesn't seem to truly be ineffectual.

**Comment by gordonklaus** [comment]
In the code you linked, `query` is assigned and then never used after the `if/else` block.  Perhaps on [line 165](https://github.com/ocket8888/trafficcontrol/blob/to/restructure-roles/traffic_ops/traffic_ops_golang/user/user.go#L165) you meant to write `query` instead of `readQuery`?

**Comment by ocket8888** [comment]
... yes, yes I did.

I guess I was just confused what this linter actually does; the README just says _"Detect ineffectual assignments in Go code."_. I thought that meant things like `a = a` and `a = a + 1` which should be `a += 1` or something.

False false positive.

**Comment by gordonklaus** [comment]
Thanks for the feedback, I updated the README now in 0589229737b250c0aa92942483f6e8e58c6affaa.
