### ISSUE TITLE
allow ineffectual assignments to pointers

### ISSUE THREAD

**Issue by mpldr** [gordonklaus/ineffassign#62]
```go
func (s *Token) RPCCreate(req CreationRequest, response *Token) {               
        response = NewPermanent(req.Application, &req.Permissions, req.Expiration)
}
```

This triggers an ineffectual assignment warning but it is not. The response is evaluated by the request sender.

**Comment by gordonklaus** [comment]
You misunderstand how pointers (and pass-by-value) work.  The caller of RPCCreate will not see its response modified.  Try removing the assignment and see if anything changes (nothing will).

If you want to modify what response _points to_, then you need to write something like:
```
        *response = *NewPermanent(req.Application, &req.Permissions, req.Expiration)
```

but that code kind of smells.  More likely `RPCCreate` should _return_ the response.

**Comment by mpldr** [comment]
Thank you very much. I didn't even notice that I missed dereferencing it.

> but that code kind of smells. More likely RPCCreate should return the response.

I agree, would be more intuitive, but that's unfortunately not how net/rpc works.
