### ISSUE TITLE
What is causing this ineffassign?

### ISSUE THREAD

**Issue by TomWright** [gordonklaus/ineffassign#66]
Hi there,

I can see in my goreportcard result that I have an ineffassign: https://goreportcard.com/report/github.com/TomWright/dasel

It's highlighting [line 281](https://github.com/TomWright/dasel/blob/40d70222a2ec435bd518614425b55728783263e4/internal/command/put.go#L281) (line 2 in this snippet):
```go
cmd.AddCommand(
	putStringCommand(),
	putBoolCommand(),
	putIntCommand(),
	putObjectCommand(),
	putDocumentCommand(),
)
```

From the README:
> An assignment is ineffectual if the variable assigned is not thereafter used.

I don't understand why this line has been highlighted since:
1. No variable is assigned on that line
2. The return value is passed straight into a func where it is immediately used

Have I missed something or would this be considered a bug?

**Comment by gordonklaus** [comment]
Looking closer at the goreportcard result, it says:
`Line 281: warning: undeclared name: putStringCommand (ineffassign)`

This isn't an ineffectual assignment, but an error loading the code.

When I clone your repository and run `ineffassign ./...`, I get no errors.  So, this error must be a result of the way goreportcard runs the tool.  I see that it uses gometalinter, which is deprecated, FWIW.

I can sort of reproduce the error by running `ineffassign internal/command/put.go`, but then, of course, I get `undeclared name` errors for all of the `put*Command` functions.  Perhaps goreportcard/gometalinter is truncating its output to only show the first couple of errors (but why the duplicate)?

Anyway, I suggest you take this up with the folks at goreportcard.

**Comment by TomWright** [comment]
Thanks for the quick reply and clear explanation 👍
