### ISSUE TITLE
"Ineffectual assignment" false positive when var used in deferred function call

### ISSUE THREAD

**Issue by danutavadanei** [gordonklaus/ineffassign#71]
ineffassign version: last version available
go version: go version go1.18.3

Running the linter when interacting with a var after passing it to a deferred function call marks it as `ineffectual assignment`

```go
package main

import "errors"

func shutdown(err error) {
    if err != nil {
        panic(err)
    }
}

func TestLint() {
    var err error
    defer shutdown(err)

    if true {
        err = errors.New("new error message") // test.go:16:9: ineffectual assignment to err
    }
}
```

Expectation: should not reported.

Output
```
ineffassign ./...
go-lint-issue/cmd/test.go:16:9: ineffectual assignment to err
```

**Comment by gordonklaus** [comment]
Arguments to a deferred function call are evaluated at the `defer`
statement.  Your assignment to `err` doesn't have the effect that you think
it does.

**Comment by danutavadanei** [comment]
Got it, thanks! Fixed my code with `defer func() { shutdown(err) }()`
