### ISSUE TITLE
[PANIC] Running against large code-base after update

### ISSUE THREAD

**Issue by tarndt** [gordonklaus/ineffassign#75]
Per the discussion here https://github.com/gordonklaus/ineffassign/commit/ad4f15b778755ab69997e5ca30c4beecf7fb2c14#r85282476 ineffassign now panics after https://github.com/gordonklaus/ineffassign/commit/ad4f15b778755ab69997e5ca30c4beecf7fb2c14 was merged.

**Comment by gordonklaus** [comment]
Sorry about that.  Thanks for letting me know.  Should be fixed now.
