### ISSUE TITLE
false positive for map variable

### ISSUE THREAD

**Issue by Primital** [gordonklaus/ineffassign#76]
We ran into an issue with this tool reporting an ineffectual assignment when reassigning the same value as the `exists` value when assigning a new value from a map.

```
	predictions, ok := predMap[something[0]]
	if !ok {
		t.Fatalf("...")
	}
        firstStop, ok := predictions[someID]
	if !ok {
		t.Fatalf("...")
	}
	..something...
	secondStop, ok := predictions[anotherID]
	if !ok {
		t.Fatalf("...")
	}
```
The linter tells me `ok` is an ineffectual assignment on the second and third assignment even though it is immediately checked on the next line.

To solve this we had to rewrite these tests as
```
	predictions, ok := predMap[something[0]]
	if !ok {
		t.Fatalf("...")
	}
        var firstStop, secondStop SomeStruct
        firstStop, ok = predictions[someID]
	if !ok {
		t.Fatalf("...")
	}
	..something...
	secondStop, ok = predictions[anotherID]
	if !ok {
		t.Fatalf("...")
	}
```

**Comment by gordonklaus** [comment]
Thanks for the report, and sorry for the slow reply.

I'm unable to reproduce the issue.  Can you make sure you're using the latest version of the tool and provide a self-contained reproducer or a link to the actual code?
