### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by tanji** [gordonklaus/ineffassign#9]
Example from my code:
```
	for _, server := range servers {
		f := false
		if server.State == stateUnconn || server.State == stateFailed {
			if f == false {
				f = true
				vy++
			}
```

Error message:
f assigned and not used (ineffassign)

f has already been assigned in the outer loop so error should not happen when f is set to true.

**Comment by gordonklaus** [comment]
`f` is assigned (`f = true`) and then not used (unless it is used on a line beyond what you've posted).  Maybe you meant to declare `f` outside the loop?  Or meant to write `for server.State == ...` instead of `if server.State == ...`?

**Comment by tanji** [comment]
You are right, f should have been declared outside the loop...
Sorry for missing that obvious one :(
